version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: stockhub_nginx
    volumes:
      - /pso/stock-hub/public:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - stockhub-network
    ports:
      - "8081:8081"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stockhub_app
    env_file:
      - .env
    working_dir: /var/www/html
    volumes:
      - /pso/stock-hub:/var/www/html
    networks:
      - stockhub-network
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: stockhub_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: stockhub
      MYSQL_USER: stockhubuser
      MYSQL_PASSWORD: stockhubpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - stockhub-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: stockhub_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: stockhubuser
      PMA_PASSWORD: stockhubpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - stockhub-network

volumes:
  db_data:

networks:
  stockhub-network:
    name: stockhub-network
    driver: bridge
