name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: stockhub
          MYSQL_USER: stockhubuser
          MYSQL_PASSWORD: stockhubpassword
          MYSQL_ROOT_PASSWORD: rootpassword
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install PHP Extensions
        run: sudo apt-get install -y php-zip

      - name: Install Google Chrome (Stable Version)
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Debug Google Chrome Version
        run: google-chrome --version

      - name: Download and Use Closest Matching Chromedriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
          MAJOR_VERSION=$(echo "$CHROME_VERSION" | cut -d '.' -f 1)
          echo "Detected Chrome version: $CHROME_VERSION"
          if [ "$MAJOR_VERSION" -eq 131 ]; then
            echo "No exact Chromedriver version available for Chrome 131. Attempting to use latest Chromedriver."
            curl -s -o chromedriver.zip https://chromedriver.storage.googleapis.com/LATEST_RELEASE/chromedriver_linux64.zip
          else
            CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$MAJOR_VERSION)
            echo "Matching Chromedriver version: $CHROMEDRIVER_VERSION"
            curl -s -o chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          fi
          unzip -o chromedriver.zip -d ./vendor/laravel/dusk/bin/
          chmod +x ./vendor/laravel/dusk/bin/chromedriver

      - name: Verify Chromedriver Path
        run: ls -la ./vendor/laravel/dusk/bin/

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Configure Testing Environment
        run: |
          cp .env.example .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=stockhub/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=stockhubuser/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=stockhubpassword/' .env

      - name: Run Database Migrations and Seed
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: stockhub
          DB_USERNAME: stockhubuser
          DB_PASSWORD: stockhubpassword
        run: |
          php artisan migrate --force
          php artisan db:seed

      - name: Generate APP_KEY
        run: php artisan key:generate

      - name: Run Unit Tests (PHPUnit)
        run: php artisan test

      - name: Run Static Analysis (PHPStan)
        run: ./vendor/bin/phpstan analyse --level=0 app

      - name: Run PHP_CodeSniffer Fixer
        run: ./vendor/bin/phpcbf --standard=PSR12 app

      - name: Run PHP_CodeSniffer
        run: ./vendor/bin/phpcs --standard=PSR12 app

      - name: Run Laravel Dusk Tests
        env:
          APP_ENV: testing
        run: php artisan dusk

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        env:
          SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > /tmp/vps_key
          chmod 600 /tmp/vps_key
          scp -o StrictHostKeyChecking=no -i /tmp/vps_key -r * user@your_vps_ip:/path/to/project || exit 1
          ssh -o StrictHostKeyChecking=no -i /tmp/vps_key user@your_vps_ip << EOF || exit 1
            cd /path/to/project
            docker-compose down
            docker-compose up -d --build
          EOF
