name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Extract SSH Key
      - name: Extract SSH Key
        run: |
          mkdir -p ~/.ssh
          tar -xvf key.tar.gz -C ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      # Install Dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      # Deploy Code to VPS
      - name: Deploy to VPS
        env:
          DEPLOY_PATH: /pso/stock-hub
        run: |
          rsync -avz --exclude '.git' --exclude 'key.tar.gz' ./ root@217.15.160.69:${{ env.DEPLOY_PATH }}
          ssh root@217.15.160.69 "cd ${{ env.DEPLOY_PATH }} && composer install && php artisan migrate --force"

      # Reload Web Server
      - name: Reload Web Server
        run: |
          ssh root@217.15.160.69 "systemctl reload nginx"
