name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo_mysql, bcmath
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Set Up Environment
        run: cp .env.example .env

      - name: Generate APP_KEY
        run: php artisan key:generate

      - name: Run Unit Tests (PHPUnit)
        run: php artisan test

      - name: Run Static Analysis (PHPStan)
        run: |
          composer require --dev phpstan/phpstan
          ./vendor/bin/phpstan analyse --level=7 app

      - name: Run PHP_CodeSniffer
        run: |
          composer require --dev squizlabs/php_codesniffer
          ./vendor/bin/phpcs --standard=PSR12 app

      - name: Install Laravel Dusk
        run: |
          composer require --dev laravel/dusk
          php artisan dusk:install

      - name: Run End-to-End Tests (Laravel Dusk)
        env:
          APP_ENV: testing
          APP_KEY: base64:SNzPdetOFSUqu+XhDrVaGkzsMkXUMQ4tK4AfSdJZoog=  # Ganti dengan APP_KEY yang valid
        run: php artisan dusk

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        env:
          SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > /tmp/vps_key
          chmod 600 /tmp/vps_key
          scp -o StrictHostKeyChecking=no -i /tmp/vps_key -r * user@your_vps_ip:/path/to/project
          ssh -o StrictHostKeyChecking=no -i /tmp/vps_key user@your_vps_ip << EOF
            cd /path/to/project
            docker-compose down
            docker-compose up -d --build
          EOF
