name: Run Security Testing

on:
  push:
    branches:
      - security-testing
  pull_request:
    branches:
      - security-testing

jobs:
  security-testing:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql, zip

      # 3. Clear Composer Cache
      - name: Clear Composer Cache
        run: composer clear-cache

      # 4. Install Composer dependencies
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # 5. Verify Composer Dependencies
      - name: Verify Composer Dependencies
        run: composer show

      # 6. Install Pest (if missing)
      - name: Install Pest
        run: composer require pestphp/pest --dev

      # 7. Debug Vendor Directory
      - name: Check Vendor Bin Directory
        run: ls -l ./vendor/bin/

      # 8. Run Tests with Pest
      - name: Run Tests with Pest
        run: ./vendor/bin/pest || echo "Pest tests failed"

      # 9. Debugging Steps
      - name: Check PHP Info
        run: php -i

      - name: Check Pest Version
        run: ./vendor/bin/pest --version

      - name: Check Composer Version
        run: composer --version
